//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaRooms.AutomationFramework.Tests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Live")]
        public string TestingEnvironment {
            get {
                return ((string)(this["TestingEnvironment"]));
            }
            set {
                this["TestingEnvironment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:4444/wd/hub")]
        public string SeleniumRemoteServerURL {
            get {
                return ((string)(this["SeleniumRemoteServerURL"]));
            }
            set {
                this["SeleniumRemoteServerURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SeleniumExecuteLocally {
            get {
                return ((bool)(this["SeleniumExecuteLocally"]));
            }
            set {
                this["SeleniumExecuteLocally"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chrome")]
        public string SeleniumBrowser {
            get {
                return ((string)(this["SeleniumBrowser"]));
            }
            set {
                this["SeleniumBrowser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ec2-54-229-207-216.eu-west-1.compute.amazonaws.com;Initial Catalog=Sy" +
            "stemsManagement;Persist Security Info=True;User ID=sa;Password=R0X13S;MultipleAc" +
            "tiveResultSets=True")]
        public string AutomationFrameworkConnectionString {
            get {
                return ((string)(this["AutomationFrameworkConnectionString"]));
            }
            set {
                this["AutomationFrameworkConnectionString"] = value;
            }
        }
    }
}
